---
Organizations:
    - &OrdererOrganization
        Name: OrdererOrganizationMSP
        ID: OrdererOrganizationMSP
        MSPDir: ../crypto-config/ordererOrganizations/example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererOrganizationMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererOrganizationMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererOrganizationMSP.admin')"

    - &DAIICTOrganization
        Name: DAIICTOrganizationMSP
        ID: DAIICTOrganizationMSP
        MSPDir: ../crypto-config/peerOrganizations/daiict.example.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('DAIICTOrganizationMSP.admin', 'DAIICTOrganizationMSP.peer', 'DAIICTOrganizationMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('DAIICTOrganizationMSP.admin', 'DAIICTOrganizationMSP.peer', 'DAIICTOrganizationMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('DAIICTOrganizationMSP.admin')"
        AnchorPeers:
            - Host: peer0.daiict.example.com
              Port: 7051

Capabilities:
    Channel: &ChannelCapabilities
        V1_3: true
    Orderer: &OrdererCapabilities
        V1_1: true
    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: kafka
    Addresses:
        - orderer0.example.com:7050
        - orderer1.example.com:7050
        - orderer2.example.com:7050

    BatchTimeout: 1s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 800 KB

    Kafka:
        Brokers:
            - kafka0:9092
            - kafka1:9092
            - kafka2:9092
            - kafka3:9092

    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    TwoOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrganization
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *DAIICTOrganization
                 
    DAChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *DAIICTOrganization
            Capabilities:
                <<: *ApplicationCapabilities