version: '2'

services:

  peer0.daiict.example.com:
    container_name: peer0.daiict.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.daiict.example.com
      - CORE_PEER_ADDRESS=peer0.daiict.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.daiict.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.daiict.example.com:7051
      - CORE_PEER_LOCALMSPID=DAIICTOrganizationMSP
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.daiict.example.com:5984
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/daiict.example.com/peers/peer0.daiict.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/daiict.example.com/peers/peer0.daiict.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.daiict.example.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer1.daiict.example.com:
    container_name: peer1.daiict.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.daiict.example.com
      - CORE_PEER_ADDRESS=peer1.daiict.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.daiict.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.daiict.example.com:7051
      - CORE_PEER_LOCALMSPID=DAIICTOrganizationMSP
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer1.daiict.example.com:5984      
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/daiict.example.com/peers/peer1.daiict.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/daiict.example.com/peers/peer1.daiict.example.com/tls:/etc/hyperledger/fabric/tls
        - peer1.daiict.example.com:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053